// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2iFF5KESQtZEVYT0duHwlrZ2908GOLS0',
    appId: '1:229756670121:web:9bb21cbf1957df4d7cd9b8',
    messagingSenderId: '229756670121',
    projectId: 'gifthunt-e922b',
    authDomain: 'gifthunt-e922b.firebaseapp.com',
    storageBucket: 'gifthunt-e922b.firebasestorage.app',
    measurementId: 'G-HR1WZQTGD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjfin9dwulDy8aaMb8oaOXROQfTl1bL8',
    appId: '1:229756670121:android:ccbdbb2a78a49dcf7cd9b8',
    messagingSenderId: '229756670121',
    projectId: 'gifthunt-e922b',
    storageBucket: 'gifthunt-e922b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5ORP8Br4AXZ-w5bxUAxX6mke_2kfjA0',
    appId: '1:229756670121:ios:fc98df31a107cb927cd9b8',
    messagingSenderId: '229756670121',
    projectId: 'gifthunt-e922b',
    storageBucket: 'gifthunt-e922b.firebasestorage.app',
    iosBundleId: 'com.example.gifthunt',
  );
}
